[WIP] Stripe ConnectとStripe CheckoutでCtoC決済をする
gaiax/rails-stripe-connect-sample pull request #3
Opened 2020-05-22 11:17 UTC by ichigotake

READMEとプルリクのコメントを整えたらWIPを外します

2020-05-26 06:47 UTC, aramsan commented
README.mdで2点ほど不備がありました。

```
### MySQLを起動する
$ docker-compose -d db
```
docker-compose up -d db
ですね

bundle installの前に以下を追加してください
```
### macOSの場合
$ bundle config --local build.mysql2 "--with-ldflags=-L/usr/local/opt/openssl/lib"
```

また、起動後、たろう商店で購入しても何も起きませんでした。
確認をお願いたします。

2020-05-28 07:02 UTC, ichigotake commented
READMEは修正しました。動作確認は今からやります。

2020-06-04 08:59 UTC, ichigotake commented on app/views/connect_accounts/new.html.erb
> +      <% if @individual_form.errors.messages[:email].any? %>
コントローラーで `@individual_form.validate` を実行しているのにエラーメッセージが表示されません。

コントローラーでは `@individual_form.errors` にオブジェクトがあっても、ビューでは何故か空になります。原因は調査中です。

2020-06-10 05:51 UTC, aramsan requested changes
決済できない件で、気になる点が2つあったので試してみてほしいです。

2020-06-10 05:51 UTC, aramsan commented on app/controllers/connect_accounts_controller.rb
> +          address_kanji: {
実験的に、address_kana も作ってみてください。

2020-06-10 05:51 UTC, aramsan commented on app/controllers/connect_accounts_controller.rb
> +          gender: @individual_form.gender,
external_account
すなわち振り込み用の銀行口座の登録も必要です。追加をお願いします。
[Stripe Connect 101](https://qiita.com/y_toku/items/7bfa42793801dfc5415d)
入金についてのところに書かれている情報がないと、登録が完了しないかと。

2020-06-15 03:28 UTC, ichigotake commented on app/controllers/connect_accounts_controller.rb
> +          gender: @individual_form.gender,
はい

2020-06-15 08:00 UTC, ichigotake commented on app/controllers/connect_accounts_controller.rb
> +          gender: @individual_form.gender,
pushしました。 `db:migrate` を実行してから確認お願いします。

2020-06-23 05:22 UTC, aramsan commented on app/controllers/connect_accounts_controller.rb
> +          address_kanji: {
kanaを作った時点で修正されたことを確認しました！ありがとうございます！

2020-06-23 05:22 UTC, aramsan commented on app/controllers/connect_accounts_controller.rb
> +          gender: @individual_form.gender,
こちらも、フォーム作っていただきありがとうございます！修正されています！

2020-06-23 05:24 UTC, aramsan commented on app/views/connect_accounts/new.html.erb
> +      <% if @individual_form.errors.messages[:email].any? %>
Connect Onboarding for Custom Accounts
によって、回避されたことを確認しました。ありがとうございました！

2020-06-23 05:26 UTC, aramsan approved these changes

2020-06-23 05:27 UTC, aramsan commented
長いことかかりましたがLGTMです！ありがとうございます！

2021-04-05 04:55 UTC, merged